version: '2'
services:
  anaconda3-jupyter:
    build:
      context: .
    ports:
     - "8888:8888"
    environment:
     - jupyter_password=password
    command: bash -c "python /root/passgen.py && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser --allow-root"
